# Generated by Django 2.0.5 on 2018-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='alarm',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
