# Generated by Django 2.1 on 2018-08-27 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'permissions': (('run_rules', 'Can run decision making process'), ('manage_rules', 'Can make/change/delete rules'))},
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='chance',
            field=models.SmallIntegerField(blank=True, verbose_name='Certainty that patient has a disease'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.Disease', verbose_name='Diagnosed disease'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctor responsable for diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='highTemp',
            field=models.BooleanField(verbose_name='User had high temperature'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='medicine',
            field=models.ManyToManyField(to='diagnostics.Medicine', verbose_name='Prescribed medicines'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='temp',
            field=models.SmallIntegerField(blank=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='regularsympt',
            field=models.ManyToManyField(related_name='regular_syndrome', to='diagnostics.Syndrome', verbose_name='General syndromes'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='strongsympt',
            field=models.ManyToManyField(blank=True, related_name='strong_syndrome', to='diagnostics.Syndrome', verbose_name='Specific syndromes'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ingredient',
            field=models.ManyToManyField(to='diagnostics.Ingredient', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medtype',
            field=models.CharField(choices=[('0', 'Analgesic'), ('1', 'Antibiotic'), ('2', 'Other')], max_length=1, verbose_name='Medicine type'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='monitoringinfo',
            name='heartratebeat',
            field=models.SmallIntegerField(verbose_name='Heartbeat rate'),
        ),
        migrations.AlterField(
            model_name='monitoringinfo',
            name='liquidlevel',
            field=models.SmallIntegerField(verbose_name='Amount of urine produced'),
        ),
        migrations.AlterField(
            model_name='monitoringinfo',
            name='oxygenlevel',
            field=models.SmallIntegerField(verbose_name='Level of oxygen in blood'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alergying',
            field=models.ManyToManyField(blank=True, to='diagnostics.Ingredient', verbose_name='Allergic to ingredients'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alergymed',
            field=models.ManyToManyField(blank=True, to='diagnostics.Medicine', verbose_name='Allergic to medicines'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='monitoring',
            field=models.ManyToManyField(blank=True, to='diagnostics.MonitoringInfo', verbose_name='Monitoring data records'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='content',
            field=models.CharField(max_length=10000, verbose_name='Rule'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='ruletype',
            field=models.CharField(choices=[('0', 'Disease decision making rule'), ('1', 'Patient alergy detection rule'), ('2', 'Find disease symptoms rule'), ('3', 'Detect disease based on symptoms rule'), ('4', 'Monitoring alarm rule'), ('5', 'Rule for grouping patients')], max_length=1, verbose_name='Rule type'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Rule title'),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
