# Generated by Django 2.0.5 on 2018-09-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_auto_20180911_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rulesType', models.CharField(choices=[('0', 'Disease decision making rule'), ('1', 'Patient alergy detection rule'), ('2', 'Find disease symptoms rule'), ('3', 'Detect disease based on symptoms rule'), ('4', 'Monitoring alarm rule'), ('5', 'Rule for grouping patients')], max_length=1)),
                ('rules', models.ManyToManyField(to='diagnostics.Rule')),
            ],
        ),
        migrations.AddField(
            model_name='symptom',
            name='technical',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='alarm',
            unique_together={('patientId', 'alarm')},
        ),
    ]
