# Generated by Django 2.0.5 on 2018-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_auto_20180912_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='regularsympt',
            field=models.ManyToManyField(related_name='regular_symptoms', to='diagnostics.Symptom', verbose_name='General symptoms'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='strongsympt',
            field=models.ManyToManyField(blank=True, related_name='strong_symptoms', to='diagnostics.Symptom', verbose_name='Specific symptoms'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='Rule title'),
        ),
    ]
