# Generated by Django 2.0.5 on 2018-09-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_auto_20180904_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulefilecreator',
            name='fileRules',
        ),
        migrations.DeleteModel(
            name='ruleFileCreator',
        ),
    ]
