# Generated by Django 2.0.5 on 2018-09-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_auto_20180905_1730'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filerule',
            unique_together={('extendedRule', 'params')},
        ),
    ]
