# Generated by Django 2.0.5 on 2018-09-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_auto_20180913_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleset',
            name='rules',
        ),
        migrations.AlterUniqueTogether(
            name='alarm',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='RuleSet',
        ),
    ]
