# Generated by Django 2.0.5 on 2018-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0006_auto_20180907_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Rule priority'),
            preserve_default=False,
        ),
    ]
