# Generated by Django 2.0.5 on 2018-09-10 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0007_rule_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostics.Disease', verbose_name='Diagnosed disease'),
        ),
    ]
