# Generated by Django 2.0.5 on 2018-09-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0008_auto_20180910_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('solved', models.BooleanField()),
                ('patientId', models.IntegerField()),
            ],
        ),
    ]
