# Generated by Django 2.0.5 on 2018-09-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0009_alarm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='title',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='alarm',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
