# Generated by Django 2.0.5 on 2018-09-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0010_auto_20180910_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='time',
        ),
    ]
